### ISSUE TITLE
Workshop 6 part 2

### ISSUE THREAD

**Issue by zakariyams** [AdeptiC/Tower-Defence-Game#56]
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work; add unit tests when appropriate.
- [x] List the issues and PRs you worked on during the week in the "Lecture 10 checklist" issue.
- [x] Define a few project goals for the upcoming weeks, create them as issues, list them in the "Lecture 10 checklist" issue.
- [x] Make a new release following Semantic Versioning rules.

**Comment by zakariyams** [comment]
Some of the goals for the upcoming weeks, see issues #59 #58  #57

**Comment by Yoosseph** [comment]
During the week we have been working issues #50 and #57. 
Relevant PRs: #67 #66 #65 #61 
We have also worked with workshops during the week.
